//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "133.0.0+g2197e2d+chromium-133.0.6886.0"
#define CEF_VERSION_MAJOR 133
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 0
#define CEF_COMMIT_NUMBER 3111
#define CEF_COMMIT_HASH "2197e2d63cf5e5b3d20c26949e24bb7f886cbf9e"
// clang-format on

#endif // CefVersion
