//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "134.3.9+g5dc6f2f+chromium-134.0.6998.178"
#define CEF_VERSION_MAJOR 134
#define CEF_VERSION_MINOR 3
#define CEF_VERSION_PATCH 9
#define CEF_COMMIT_NUMBER 3158
#define CEF_COMMIT_HASH "5dc6f2f29c7466f6e9ab9773e36de4b28e59c1f3"
// clang-format on

#endif // CefVersion
