//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "135.0.17+gcbc1c5b+chromium-135.0.7049.52"
#define CEF_VERSION_MAJOR 135
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 17
#define CEF_COMMIT_NUMBER 3166
#define CEF_COMMIT_HASH "cbc1c5b766aec457ec3a565ea4c738bfc6066564"
// clang-format on

#endif // CefVersion
